# Generated by Django 5.2.7 on 2025-11-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_todo_status_9f7c48_idx',
            old_name='my_custom_t_status_0c4346_idx',
        ),
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
