# Generated by Django 5.2.7 on 2025-11-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_my_custom_t_status_0c4346_idx_todos_todo_status_9f7c48_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_status_ec7fa7_idx',
            old_name='todos_todo_status_9f7c48_idx',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
