# Generated by Django 5.2.7 on 2025-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_todos_todo_status_9f7c48_idx_todos_status_ec7fa7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
